# Generated by Django 5.1.4 on 2025-01-22 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_date', models.DateField()),
                ('vacancy', models.CharField(choices=[('instructor', 'Инструктор'), ('doctor', 'Медик')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('tel', models.CharField(max_length=12, unique=True)),
                ('birth_date', models.DateField()),
                ('info', models.CharField(max_length=254)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], max_length=10)),
                ('registered_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HikeDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(limit_choices_to={'vacancy': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hike')),
            ],
        ),
        migrations.CreateModel(
            name='HikeInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hike')),
                ('instructor', models.ForeignKey(limit_choices_to={'vacancy': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HikeTourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hike')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tourist')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hike')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tourist')),
            ],
        ),
        migrations.AddField(
            model_name='tourist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
