# Generated by Django 5.1.4 on 2025-01-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='doctors',
            field=models.ManyToManyField(related_name='hikes_as_doctor', through='main.HikeDoctor', to='main.employee'),
        ),
        migrations.AddField(
            model_name='hike',
            name='instructors',
            field=models.ManyToManyField(related_name='hikes_as_instructor', through='main.HikeInstructor', to='main.employee'),
        ),
        migrations.AddField(
            model_name='hike',
            name='tourists',
            field=models.ManyToManyField(through='main.HikeTourist', to='main.tourist'),
        ),
        migrations.AlterUniqueTogether(
            name='hikedoctor',
            unique_together={('hike', 'doctor')},
        ),
        migrations.AlterUniqueTogether(
            name='hikeinstructor',
            unique_together={('hike', 'instructor')},
        ),
        migrations.AlterUniqueTogether(
            name='hiketourist',
            unique_together={('hike', 'tourist')},
        ),
    ]
