# Generated by Django 5.1.4 on 2025-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_hike_doctors_hike_instructors_hike_tourists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('good', 'Принята'), ('bad', 'Отвергнута')], max_length=10),
        ),
    ]
